"""ETL for Yelp business and review enrichment.

Default behavior:
- first try ``data/raw/yelp_reviews_fusion.csv`` (generated by Fusion fetch script)
- fallback to ``YELP_DATA_PATH`` env var when default file is missing
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

import pandas as pd

from .base import DatasetSpec, build_empty_frame

logger = logging.getLogger(__name__)
_DEFAULT_FUSION_REVIEW_PATH = Path("data/raw/yelp_reviews_fusion.csv")
_DEFAULT_FUSION_BUSINESS_PATH = Path("data/raw/yelp_business.csv")

DATASET_SPEC = DatasetSpec(
    name="yelp",
    owner="data",
    spatial_unit="restaurant",
    time_grain="date",
    description="Review text and business metadata for enrichment only after coverage audit.",
    columns=("review_date", "business_id", "restaurant_id", "rating", "review_text"),
)


def run_placeholder_etl() -> pd.DataFrame:
    return build_empty_frame(DATASET_SPEC)


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------


def _load_local() -> pd.DataFrame:
    """Load Yelp reviews from default Fusion CSV or env-configured local file."""
    if _DEFAULT_FUSION_REVIEW_PATH.is_file():
        path = _DEFAULT_FUSION_REVIEW_PATH
        logger.info("etl_yelp: loading default Fusion review file %s", path)
    else:
        path_str = os.environ.get("YELP_DATA_PATH", "")
        if not path_str:
            raise RuntimeError(
                "etl_yelp: missing Yelp input file. Expected default "
                f"{_DEFAULT_FUSION_REVIEW_PATH} or YELP_DATA_PATH env var."
            )
        path = Path(path_str)
        if not path.is_file():
            raise FileNotFoundError(f"etl_yelp: YELP_DATA_PATH={path} does not exist")
        logger.info("etl_yelp: loading from YELP_DATA_PATH %s", path)

    logger.info("etl_yelp: loading from local file %s", path)
    if path.suffix.lower() == ".json":
        return pd.read_json(path, lines=True)
    return pd.read_csv(path)


def _load_business() -> pd.DataFrame:
    """Load Yelp business lat/lon from default business CSV.

    Returns a DataFrame with (id, latitude, longitude) or empty if file missing.
    """
    if not _DEFAULT_FUSION_BUSINESS_PATH.is_file():
        logger.warning("etl_yelp: business file not found at %s — skipping geo join", _DEFAULT_FUSION_BUSINESS_PATH)
        return pd.DataFrame(columns=["id", "latitude", "longitude"])
    try:
        df = pd.read_csv(_DEFAULT_FUSION_BUSINESS_PATH, usecols=["id", "latitude", "longitude"])
        df["latitude"] = pd.to_numeric(df["latitude"], errors="coerce")
        df["longitude"] = pd.to_numeric(df["longitude"], errors="coerce")
        return df.dropna(subset=["latitude", "longitude"])
    except Exception as exc:
        logger.warning("etl_yelp: could not load business file: %s", exc)
        return pd.DataFrame(columns=["id", "latitude", "longitude"])


def run_etl(limit: int = 50000) -> pd.DataFrame:  # noqa: ARG001
    """Load real Yelp data from local file and enrich with business lat/lon."""
    reviews = _load_local()
    business = _load_business()

    if not business.empty and "business_id" in reviews.columns:
        reviews = reviews.merge(
            business.rename(columns={"id": "business_id"}),
            on="business_id",
            how="left",
        )

    return reviews
